### ISSUE TITLE
Chore: Add Tests for Drag-and-Drop Example 🙏 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-alpine.js#12]
As noted in: https://github.com/dwyl/learn-alpine.js/pull/5#pullrequestreview-1166574548 the test coverage in this repo is quite low. 

# Todo

+ [ ] Write some tests for the drag-and-drop feature 🧑‍💻 
  + [ ] If we need to consider a front-end testing framework, please comment below! 
  e.g: https://github.com/dwyl/learn-phoenix-framework/issues/149 
+ [ ] _Explain_ how the tests work. 👨‍🏫 
+ [ ] Add Codecov badge ➕ 
+ [ ] Restore order to the Universe! 🦸‍♀️
